language: java
script: mvn cobertura:cobertura
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  api_key: 3d76fbf274cd484f083d8beac0b75a4a4ddd8dee
  file_glob: true
  file: target/*.jar
  skip_cleanup: true
  draft: true
